# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConectadoNaturaleza' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
    pod 'Alamofire', '~> 5.1'
    pod 'ObjectMapper', '~> 3.5.2'
    pod 'AlamofireObjectMapper', '~> 5.2'
  # Pods for ConectadoNaturaleza

  target 'ConectadoNaturalezaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConectadoNaturalezaUITests' do
    # Pods for testing
  end

end
